### ISSUE TITLE
CSS modules is not generated correctly

### ISSUE THREAD

**Issue by serkangunes** [haraldrudell/react-rollup#1]
create-react-app comes CSS modules enabled by default. 
When you use the lib-create-react-app to publish the library react-rollup is not importing the generated css.

This is esm.js
```javascript
import React from 'react';

var styles = {"test":"Test-module_test__17f0e"};

function Test(){return React.createElement("div",{className:styles.test},"test2");}

export { Test };
```

It is also generating css correctly too.
esm.css
```css
.Test-module_test__17f0e {
    width: 200px;
    height: 200px;
    background-color: magenta;
    position: absolute;
    color: white;
    top: 50%;
    left: 50%;
    font-size: 30px;
    margin-left: -100px;
    margin-top: -100px;
    text-align: center;
    line-height: 200px;
}
/*# sourceMappingURL=esm.css.map */
```

However the styles are not picked up as the js file is missing.
`import './esm.css';`
